events {}

http {

    upstream task_backend {
        server task-service-1:3002;
        server task-service-2:3002;
    }

    upstream gateway_backend {
        server gateway:3000;
    }

    upstream frontend_backend {
        server frontend:8080;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://frontend_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://gateway_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /task-api/ {
            proxy_pass http://task_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /task-test {
            proxy_pass http://task_backend/service-info;
        }
    }
}
